## Project-wide Gradle settings.
#
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
#
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# Default value: -Xmx10248m -XX:MaxPermSize=256m
# org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
#
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
#Sat Mar 12 05:53:50 MSK 2016
APP_VERSION_CODE=6966
APP_VERSION_NAME=12.9.0
FLUFFY_PATCH_VERSION=21
FLUFFY_UPDATE_MANIFEST_URL=https\://github.com/ushst/fluffyGram/releases/latest/download/update.json
FLUFFY_UPDATE_PAGE_URL=https\://github.com/ushst/fluffyGram/releases/latest
FLUFFY_BETA_UPDATE_MANIFEST_URL=https\://github.com/ushst/fluffyGram/releases/latest/download/update-beta.json
FLUFFY_BETA_UPDATE_PAGE_URL=https\://github.com/ushst/fluffyGram/releases/latest
FLUFFY_PREMIUM_PUBLIC_KEY=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA9gr5RkImxznkL1bxeRLRajNMLQR2uDkXjFiAKk7zlAIiVKvkb2rxojZb4IMsILY4/4FueJ3qy7mGeNgPVZqIQ9wi+EPIGVXCp5ibt/9HdhdX6ka2lkbgHdHqj+vcHqQa4H873MjiQlcPHmvxXKcfkAr/k/pqstQvNNSgzbBJ03aUmkrTK1uyCDy4TQxgOGSyHYKL1JeKYSNONS+u6njHcr42zHjVw2xD8bm6XedN1i6CSEEZm/vIYHoKjwsZtdmckBGj69L1SLHMUjksPIaloIlHJigBmOw93jSXM4EmfESaa7HS8NcGjYF+E9/GKbcHtrHHHxtH1Glm7K3nruktcQIDAQAB
APP_PACKAGE=org.telegram.messenger
IS_PRIVATE=false
RELEASE_KEY_PASSWORD=android
RELEASE_KEY_ALIAS=androidkey
RELEASE_STORE_PASSWORD=android
org.gradle.jvmargs=-Xmx4096M -XX:+UseParallelGC -Djava.net.preferIPv4Stack=true -Djava.net.preferIPv4Addresses=true
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.configureondemand=true
android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
android.nonFinalResIds=true
android.enableR8.fullMode=true

systemProp.org.gradle.internal.http.socketTimeout=300000
systemProp.org.gradle.internal.http.connectionTimeout=300000
systemProp.org.gradle.internal.repository.max.retries=10
systemProp.org.gradle.internal.repository.initial.backoff=500
